### ISSUE TITLE
Server down? DNS Issue?

### ISSUE THREAD

**Issue by claytonrcarter** [fuzzingbits/quiet-hacker-news#1]
Hi there, thanks for hosting https://quiethackernews.com/. FWIW: it appears to be down and has been for a few days. The error appears to be a DNS issue:

```sh
$ host quiethackernews.com
Host quiethackernews.com not found: 2(SERVFAIL)
$ dig quiethackernews.com

; <<>> DiG 9.10.6 <<>> quiethackernews.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 22819
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; OPT=15: 00 16 ("..")
;; QUESTION SECTION:
;quiethackernews.com.		IN	A

;; Query time: 420 msec
;; SERVER: 192.168.0.104#53(192.168.0.104)
;; WHEN: Fri Jun 04 11:07:59 EDT 2021
;; MSG SIZE  rcvd: 54

$ curl quiethackernews.com
curl: (6) Could not resolve host: quiethackernews.com
```

(these queryies are going though a PiHole, but the results appear to be the same when it is disabled)

**Comment by aaronellington** [comment]
@claytonrcarter Sorry! I was not aware that anyone else was using this. :) 

I recently moved to a different host. I just updated the readme with the new URL. <3 

https://quiet-hacker-news.appbyte.net/

**Comment by claytonrcarter** [comment]
Oh, great. Thank you! No worries, I appreciate you hosting it. BTW I'd be happy to send some $$ your way to offset some of the hosting costs; I check the site daily. 😃

**Comment by aaronellington** [comment]
haha, I appreciate the offer but I'm good for now. I'm just glad you are enjoying it as much as I am. <3
